### PR TITLE
feat: add initial version of main files

### PR DESCRIPTION
**Pull request by alice-mm**
Here's the initial version. I still have work to do on tests, and I should probably extract lots of code into proper functions here and there.

### CODE REVIEW

**Review by alacambre-yseop — COMMENTED** [review]
I kinda disagree the exclusion of SC2054 and SC2088. There are just warnings, not errors so it shouldn't be a problem to keep them. You tend to say that they are useless because “you'll know that you did something wrong when it will fail during execution”.

**Comment by alice-mm** [comment]
> I kinda disagree the exclusion of SC2054 and SC2088. There are just warnings, not errors so it shouldn't be a problem to keep them. You tend to say that they are useless because “you'll know that you did something wrong when it will fail during execution”.

While I kinda understand your point, I noticed that:
* even the “info” level of shellcheck has lots of things that can be easily avoided and have disastrous effects on the code's quality, so I want to assume that only files with no message at all “pass” the test. By the way, shellcheck's exit status seems to be the same regardless of the level of the messages;
* ~SC2054 was annoying on some scripts of the suite because we had to list parameters for Spring or whatever using commas. If you think shell arrays are meant to be filled like this:~

```
t=(a,b,c,d)
```

~rather than like this:~

```
t=(a b c d)
```

~then I'm pretty sure you will find out _very quickly_ that this does not work, and stop doing that.
To me, this SC2054 thingy will just yield false positives 99 % of the times.~

It seems that enclosing the  `a,b,c` with quotes makes it clearer to shellcheck what's happening, so maybe I'll reactivate this rule indeed. :thinking:

* Regarding SC2088 (the tilde issue), I'm not even sure there is a (convenient) way to put a tilde into a string without shellcheck yelling…

```
echo '~/foo'
     ^-----^ SC2088: Tilde does not expand in quotes. Use $HOME.
```

LOL `$HOME` wouldn't be expanded either here since these are single quotes.
RE-LOL you can get rid of the warning by concatening stuff, like…

```
echo '~''/foo'
```

I don't really want to have to write things like that, dude. Another, even worse “solution” would be…

```
declare -r TILDE='~'
echo "${TILDE}/foo"
```

~So I _really_ want to get rid of that rule.~

Edit: I'm not so sure, now. Since it should occur rather rarely and can be fixed pretty easily… And most commands, when handling tildes, give error messages that can be puzzling to newbies, like…

```
alice@——:~$ file ~/.config/
/home/alice/.config/: directory
alice@——:~$ file '~/.config/'
~/.config/: cannot open `~/.config/' (No such file or directory)
```

Many people do not understand that `~` is expanded into the home path by the command interpreter, not by the command itself nor by the OS or whatever. For example here:

```
  $ bash -xc 'echo ~'
+ echo /home/alice
/home/alice
```

… when `echo` is called, the tilde has _already_ disappeared. `echo` is thus provided with a “normal” path.

… Not sure why I'm turning this comment into some kind of Bash lesson. I guess I just like talking about that stuff way too much.

**Comment by alice-mm** [comment]
Thanks for the feedback, by the way. Reactivating a rule that is easy to calm down a little feels nice.

By the way, I compiled shellcheck from sources on my machine and…

* the version number almost doubled;
* the _very annoying_ false positive that I had on associative arrays (the index being mistaken for a variable name) seems to be fixed, now, so no need for huge regexs to try to detect assoc. array declarations. :relieved:

```
sudo aptitude install cabal-install 
cabal update
git clone git@github.com:koalaman/shellcheck.git
cd shellcheck
cabal install
# … then add ~/.cabal/bin/shellcheck to the PATH.
```

**Comment by alice-mm** [comment]
Only the rule against `'foo $bar plop'` is disabled, now.

* The tilde thing is rare and rather easy to fix.
* The warning regarding output redirections became, with recent versions of shellcheck:

> To redirect stdout+stderr, 2>&1 must be last (or use '{ cmd > file; } 2>&1' to clarify).

I thought about this syntax earlier to escape the warning, but now that they mention it I have to admit it makes things far clearer indeed!

**Pull request merged**
